name: Deploy Application 

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'   

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Deploy Backend via Docker Compose on EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@$EC2_HOST << 'EOF'
            cd test/devops-interview-ultimate/backend 
            docker-compose down
            docker-compose up --build -d
          EOF
